# Writes OUTPUT, a C++ source holding every shader in SHADERS (paths separated
# by "|") as a NUL-terminated byte array, looked up by file name.
#
# Bytes rather than raw string literals: MSVC caps a single string literal at
# about 16 KB, and the model's bake shader is larger than that. Unsigned, so a
# byte over 127 is not a narrowing error -- though shaders should be ASCII,
# which is all GLSL's character set promises.
#
# Run as: cmake -DOUTPUT=... -DSHADERS=... -P EmbedShaders.cmake

string(REPLACE "|" ";" SHADERS "${SHADERS}")

set(body "// Generated by cmake/EmbedShaders.cmake from src/core/shaders. Do not edit.\n")
string(APPEND body "#include \"shaders.h\"\n\n#include <cstring>\n\nnamespace starcanopy {\nnamespace {\n\n")
set(table "")
set(index 0)
foreach(path IN LISTS SHADERS)
  get_filename_component(name "${path}" NAME)
  file(READ "${path}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND body "// ${name}\nconst unsigned char kShader${index}[] = {\n  ${bytes}0x00};\n\n")
  string(APPEND table "  {\"${name}\", reinterpret_cast<const char*>(kShader${index})},\n")
  math(EXPR index "${index} + 1")
endforeach()
string(APPEND body "struct Embedded {\n  const char* name;\n  const char* source;\n};\n\n")
string(APPEND body "const Embedded kEmbedded[] = {\n${table}};\n\n}  // namespace\n\n")
string(APPEND body "const char* shaderSource(const char* name) {\n")
string(APPEND body "  for (const Embedded& e : kEmbedded) {\n")
string(APPEND body "    if (std::strcmp(e.name, name) == 0) {\n      return e.source;\n    }\n  }\n")
string(APPEND body "  return nullptr;\n}\n\n}  // namespace starcanopy\n")

# Only touch the output when it changes, so an unrelated reconfigure does not
# rebuild the core.
set(old "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL body)
  file(WRITE "${OUTPUT}" "${body}")
endif()
